# Site settings
title: "YoungbinLab Blog"
description: "Logs of Youngbin han's Laboratory"
email: sukso96100@gmail.com

name: 'Youngbin Han'
author: 'Youngbin Han'

disqus: 'youngbinhan'
google_analytics:

paginate: 10

# url: "" # the base hostname & protocol for your site
# baseurl: "/"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: [jekyll-paginate]
