# Site settings
title: "Polymer Magazine" # Title of your site
description: "A Polymer Library based Magazine style theme for jekyll" # description of your site
email: foo@bar.com # Your Email Address

name: 'jekyll'
author: 'jekyll'

disqus: 'jekyll' # disqus shortname
github: 'jekyll' # github usernamee
facebook: 'jekyll' # facebook profile
googleplus: 'jekyll' # gplus profile
twitter: 'jekyll' # twitter username
google_analytics:

paginate: 10

# url: "" # the base hostname & protocol for your site
# baseurl: "/"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: [jekyll-paginate]
